#服务配置
server:
  port: 8887

# spring配置
spring:
  #thymeleaf模板
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

  # jdbc配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: mango
    password: root5.7.22

# mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.xlx.ssmpshiro.system.entity
#  typeEnumsPackage:
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: AUTO
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: mysql
#
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

# 自定义配置
ssmp:
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/gifCode,/,/actuator/**,/test/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403

    # 密码加密
    crypto:
      algorithmName: md5
      hashIterations: 2

  #验证码
  validateCode:
    # 宽度，默认 146px
    width: 146
    # 高度，默认 33px
    height: 33
    # 验证码字符个数，默认4个字符
    length: 4